UserInterface/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using AutoMapper;
using DataAccess.JsonModels;
using DataAccess.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using UserInterface.Models;

namespace UserInterface.Controllers
{
    public class OrderController : Controller
    {
        private readonly IHttpClientFactory httpClientFactory;
        private readonly IMapper mapper;

        public OrderController(IHttpClientFactory httpClientFactory, IMapper mapper)
        {
            this.httpClientFactory = httpClientFactory;
            this.mapper = mapper;
        }

        // GET: Order
        public async Task<ActionResult> Index()
        {
            var response = await GetResponse("AWS", "order");
            var model = JsonConvert.DeserializeObject<OrderListJsonModel>(response);
            var orders = mapper.Map<List<Order>, List<OrderViewModel>>(model.Orders);
            return View(orders);
        }

        // GET: Order/Details/5
        public async Task<ActionResult> Details(string id)
        {
            var response = await GetResponse("AWS", "order", id);
            var model = JsonConvert.DeserializeObject<OrderJsonModel>(response);
            var order = mapper.Map<OrderJsonModel, OrderViewModel>(model);
            return View(order);
        }

        // GET: Order/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Order/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(OrderViewModel model)
        {
            if (ModelState.IsValid)
            {
                var response = await PostResponse("AWS", "order", model);
                return RedirectToAction(nameof(Index));
            }

            return View(model);
        }

        // GET: Order/Edit/5
        public async Task<ActionResult> Edit(string id)
        {
            var response = await GetResponse("AWS", "order", id);
            var model = JsonConvert.DeserializeObject<OrderJsonModel>(response);
            var order = mapper.Map<OrderJsonModel, OrderViewModel>(model);
            return View(order);
        }

        // POST: Order/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(string id, OrderViewModel model)
        {
            if (ModelState.IsValid)
            {
                var response = await PutResponse("AWS", $"order/{id}", model);
                return RedirectToAction(nameof(Index));
            }

            return View(model);
        }

        // GET: Order/Delete/5
        public async Task<ActionResult> Delete(string id)
        {
            var response = await GetResponse("AWS", "order", id);
            var model = JsonConvert.DeserializeObject<OrderJsonModel>(response);
            var order = mapper.Map<OrderJsonModel, OrderViewModel>(model);
            return View(order);
        }

        // POST: Order/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(string id, OrderViewModel model)
        {
            try
            {
                var response = await DeleteResponse("AWS", $"order/{id}");
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        private async Task<string> GetResponse(string httpClient, string action,
            params string[] param)
        {
            if (param.Length > 0)
                foreach (var par in param)
                    action += "/" + par;

            var client = httpClientFactory.CreateClient(httpClient);
            var response = await client.GetStringAsync(action);
            return JsonConvert.DeserializeObject<string>(response);
        }

        private async Task<string> PostResponse(string httpClient, string action, object model)
        {
            var json = JsonConvert.SerializeObject(model);
            var data = new StringContent(json, Encoding.UTF8, "application/json");
            var client = httpClientFactory.CreateClient(httpClient);
            var response = await client.PostAsync(action, data);
            return response.Content.ReadAsStringAsync().Result;
        }

        private async Task<string> PutResponse(string httpClient, string action, object model)
        {
            var json = JsonConvert.SerializeObject(model);
            var data = new StringContent(json, Encoding.UTF8, "application/json");
            var client = httpClientFactory.CreateClient(httpClient);
            var response = await client.PutAsync(action, data);
            return response.Content.ReadAsStringAsync().Result;
        }

        private async Task<string> DeleteResponse(string httpClient, string action)
        {
            var client = httpClientFactory.CreateClient(httpClient);
            var response = await client.DeleteAsync(action);
            return response.Content.ReadAsStringAsync().Result;
        }
    }
}

UserInterface/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using AutoMapper;
using DataAccess.JsonModels;
using DataAccess.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using UserInterface.Models;

namespace UserInterface.Controllers
{
    public class PostController : Controller
    {
        private readonly IHttpClientFactory httpClientFactory;
        private readonly IMapper mapper;

        public PostController(IHttpClientFactory httpClientFactory, IMapper mapper)
        {
            this.httpClientFactory = httpClientFactory;
            this.mapper = mapper;
        }

        // GET: Post
        public async Task<ActionResult> Index()
        {
            var response = await GetResponse("AWS", "post");
            var model = JsonConvert.DeserializeObject<PostListJsonModel>(response);
            var products = mapper.Map<List<Post>, List<PostViewModel>>(model.Posts);
            return View(products);
        }

        // GET: Post/Details/5
        public async Task<ActionResult> Details(string id)
        {
            var response = await GetResponse("AWS", "post", id);
            var model = JsonConvert.DeserializeObject<PostJsonModel>(response);
            var post = mapper.Map<PostJsonModel, PostViewModel>(model);
            return View(post);
        }

        // GET: Post/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Post/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(PostViewModel model)
        {
            if (ModelState.IsValid)
            {
                var response = await PostResponse("AWS", "post", model);
                return RedirectToAction(nameof(Index));
            }

            return View(model);
        }

        // GET: Post/Edit/5
        public async Task<ActionResult> Edit(string id)
        {
            var response = await GetResponse("AWS", "post", id);
            var model = JsonConvert.DeserializeObject<PostJsonModel>(response);
            var post = mapper.Map<PostJsonModel, PostViewModel>(model);
            return View(post);
        }

        // POST: Post/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(string id, PostViewModel model)
        {
            if (ModelState.IsValid)
            {
                var response = await PutResponse("AWS", $"post/{id}", model);
                return RedirectToAction(nameof(Index));
            }

            return View(model);
        }

        // GET: Post/Delete/5
        public async Task<ActionResult> Delete(string id)
        {
            var response = await GetResponse("AWS", "post", id);
            var model = JsonConvert.DeserializeObject<PostJsonModel>(response);
            var post = mapper.Map<PostJsonModel, PostViewModel>(model);
            return View(post);
        }

        // POST: Post/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(string id, PostViewModel model)
        {
            try
            {
                var response = await DeleteResponse("AWS", $"post/{id}");
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        private async Task<string> GetResponse(string httpClient, string action,
            params string[] param)
        {
            if (param.Length > 0)
                foreach (var par in param)
                    action += "/" + par;

            var client = httpClientFactory.CreateClient(httpClient);
            var response = await client.GetStringAsync(action);
            return JsonConvert.DeserializeObject<string>(response);
        }

        private async Task<string> PostResponse(string httpClient, string action, object model)
        {
            var json = JsonConvert.SerializeObject(model);
            var data = new StringContent(json, Encoding.UTF8, "application/json");
            var client = httpClientFactory.CreateClient(httpClient);
            var response = await client.PostAsync(action, data);
            return response.Content.ReadAsStringAsync().Result;
        }

        private async Task<string> PutResponse(string httpClient, string action, object model)
        {
            var json = JsonConvert.SerializeObject(model);
            var data = new StringContent(json, Encoding.UTF8, "application/json");
            var client = httpClientFactory.CreateClient(httpClient);
            var response = await client.PutAsync(action, data);
            return response.Content.ReadAsStringAsync().Result;
        }

        private async Task<string> DeleteResponse(string httpClient, string action)
        {
            var client = httpClientFactory.CreateClient(httpClient);
            var response = await client.DeleteAsync(action);
            return response.Content.ReadAsStringAsync().Result;
        }
    }
}

UserInterface/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using AutoMapper;
using Common;
using DataAccess.JsonModels;
using DataAccess.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using UserInterface.Models;

namespace UserInterface.Controllers
{
    public class UserController : Controller
    {
        private readonly IHttpClientFactory httpClientFactory;
        private readonly IMapper mapper;

        public UserController(IHttpClientFactory httpClientFactory, IMapper mapper)
        {
            this.httpClientFactory = httpClientFactory;
            this.mapper = mapper;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var response = await GetResponse("AWS", "user");
            var model = JsonConvert.DeserializeObject<UserListJsonModel>(response);
            var users = mapper.Map<List<User>, List<UserViewModel>>(model.Users);
            return View(users);
        }

        [HttpGet]
        public async Task<IActionResult> Details(string id)
        {
            var user = await GetUserById(id);
            if(user == null) return NotFound();
            return View(user);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            var user = await GetUserById(id);
            if (user == null) return NotFound();
            return View(user);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(UserViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = mapper.Map<UserViewModel, UserJsonModel>(model);
                var response = await PostResponse("AWS", "user/edit", user);
                return RedirectToAction("Index");
            }
            return View(model);
        }

        private async Task<UserViewModel> GetUserById(string id)
        {
            var response = await GetResponse("AWS", "user", id);
            var model = JsonConvert.DeserializeObject<UserJsonModel>(response);
            if (!model.IsSuccess) return null;
            return mapper.Map<UserJsonModel, UserViewModel>(model);
        }

        private async Task<string> GetResponse(string httpClient, string action, 
            params string[] param)
        {
            if(param.Length > 0)
                foreach(var par in param)
                    action += "/" + par;

            var client = httpClientFactory.CreateClient(httpClient);
            var response = await client.GetStringAsync(action);
            return JsonConvert.DeserializeObject<string>(response);
        }

        private async Task<string> PostResponse(string httpClient, string action, object model)
        {
            var json = JsonConvert.SerializeObject(model);
            var data = new StringContent(json, Encoding.UTF8, "application/json");
            var client = httpClientFactory.CreateClient(httpClient);
            var response = await client.PostAsync(action, data);
            return response.Content.ReadAsStringAsync().Result;
        }
    }
}

UserInterface/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FoxyChmoxy</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AWS.FOXY</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                User
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <a class="dropdown-item" asp-controller="User" asp-action="Index">Get</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Product
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <a class="dropdown-item" asp-controller="Product" asp-action="Index">Get</a>
                                <a class="dropdown-item" asp-controller="Product" asp-action="Create">Add</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Order
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <a class="dropdown-item" asp-controller="Order" asp-action="Index">Get</a>
                                <a class="dropdown-item" asp-controller="Order" asp-action="Create">Add</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Post
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <a class="dropdown-item" asp-controller="Post" asp-action="Index">Get</a>
                                <a class="dropdown-item" asp-controller="Post" asp-action="Create">Add</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - AWS.FOXY - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>